bug:
  - head-branch: ['^fix/', '^bugfix/', '^hotfix/', '^patch/', '^bug/']

feature:
  - head-branch: ['^feat/', '^feature/', '^add/', '^new/']

enhancement:
  - head-branch: ['^improve/', '^refactor/', '^perf/', '^enhancement/']

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'
