changelog:
  categories:
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: ✨ New Features
      labels:
        - feature
        - enhancement
    - title: 🔧 Other Changes
      labels:
        - "*"
